### ISSUE TITLE
installation.sh Missing File Warning

### ISSUE THREAD

**Issue by MeanGr33n** [WisconsinRobotics/NetworkFirmwareUpdateRPi#10]
Summary: Running the command sh installation.sh gives a warning related to a missing file
Description: On a Linux VM (Ubuntu 18), when running 'sh installation.sh', the tester is given a warning 'WARN enoent ENOENT: no such file or directory, open '/home/$user/NetworkFirmwareUpdateRPi/package.json'. However the file 'package.json' doesn't exist in the directory as stated. There is no statement that dependencies are missing, leaving the tester unsure what could cause this. Note that the script does state: "Python 3 is installed", "node.js is installed", "npm is installed", "pip3 is installed", "flask is installed", "pytest is installed", and "coverage is installed" (afterwards the warning is shown).
Severity: Minor

**Comment by swestveer** [comment]
We have been unable to reproduce this error locally. We believe to to be a improperly installed or missing JSON package installation.
