### ISSUE TITLE
Unit Testing Errors

### ISSUE THREAD

**Issue by MeanGr33n** [WisconsinRobotics/NetworkFirmwareUpdateRPi#11]
Summary: Unable to run unit tests as prescribed in the README.
Description: Two testers, believing to have all the dependencies installed, were given an ImportError upon trying to run unit test coverage as directed in the README. One running a Linux VM, the other running a Mac, both had errors stating "ImportError: no module named flask". The installation.sh script does tell the users that flask is installed, so this error seems contradictory. As such unit tests are unable to be run and further tested.
Severity: Minor

**Comment by swestveer** [comment]
We were not able to replicate this error and believe it to be due to a failed Flask installation or it would be possible to run the front end with just the npm server and no Flask module installed.
