### ISSUE TITLE
Browser Connection issues with github and history

### ISSUE THREAD

**Issue by MaxStenklyft** [WisconsinRobotics/NetworkFirmwareUpdateRPi#12]
<img width="488" alt="screen shot 2018-12-07 at 10 04 37 am" src="https://user-images.githubusercontent.com/10049518/49660040-3ecce600-fa0b-11e8-9383-ded6666b31f8.png">

When using Chrome on a Mac, I noticed these errors in the dev tools of my browser. This is likely related to bug #7 and #8. 

We tested this on a Linux machine using FireFox and got slightly more descriptive errors. I have included a screenshot of this below. The error is more descriptive stating that Cross-Origin Requests are Blocked.

![errorformax 3](https://user-images.githubusercontent.com/10049518/49660714-e991d400-fa0c-11e8-9ba7-b8cc3fcca5f6.png)

**Comment by swestveer** [comment]
We were not able to reproduce this error on our end. This appears to be a missing or improperly installed flask module.
