### ISSUE TITLE
Upload Connection Not Working

### ISSUE THREAD

**Issue by MaxStenklyft** [WisconsinRobotics/NetworkFirmwareUpdateRPi#15]
Upload appearing not to work. Similar to the connection errors noticed for History and Github in #12. 

This would appear to inhibit the main functionality of the page. This is potentially an issue with my local workspace and may have a quick fix, but still seems potentially severe. 

I am using Crome on a Mac. 

![image](https://user-images.githubusercontent.com/10049518/49662321-0e884600-fa11-11e8-8b39-89b13cdc9f98.png)

**Comment by swestveer** [comment]
We were again unable to replicate this error localy on our machines. We believe it to be related to a missing or improperly installed Flask module
