### ISSUE TITLE
Hardware Missing

### ISSUE THREAD

**Issue by cjohnson62** [WisconsinRobotics/NetworkFirmwareUpdateRPi#3]
Summary: We do not have access to the microcontroller or hardware for testing.
Description: We only have access to the project's single webpage and cannot test anything else. The bulk of their project needs a microcontroller and special hardware to run. This is the main functionality of the project and we do not have access to it. It is hard to test a robot program without the robot.
Severity: Very high. We have access to a minimal part of the project.

**Comment by nardecchia** [comment]
Hardware will be included in future testing and debugging scenarios.
