### ISSUE TITLE
Flash Success

### ISSUE THREAD

**Issue by satyajit-patil** [WisconsinRobotics/NetworkFirmwareUpdateRPi#6]
Summary: Unsure if the flash was successful and worked as expected
Description: After uploading a file and clicking flash, I am not sure if the image flashed successfully. Since we don't have the hardware connected, I was expecting an error message.
Severity: Trivial

**Comment by nardecchia** [comment]
Flash confirmation is visible via the microcontroller itself - the microcontroller is programmed to blink when an image has been flashed to it successfully.
As detailed in our Requirements and Specifications document, we have decided not to implement confirmation/error messages via the web app at this time.
